class Contact:
    def __init__(self, firstname, lastname, company, address, mobile, middlename, nickname, title, home,
                            work, fax, email, email2, email3, homepage,
                            bmonth, byear, bday, aday, amonth,
                            new_group, ayear, address2, phone2, notes):
        self.firstname = firstname,
        self.lastname = lastname,
        self.company = company,
        self.address = address,
        self.mobile = mobile,
        self.middlename = middlename,
        self.nickname = nickname,
        self.title = title,
        self.home = home,
        self.work = work,
        self.fax = fax,
        self.email = email,
        self.email2 = email2,
        self.email3 = email3,
        self.homepage = homepage,
        self.bmonth = bmonth,
        self.byear = byear,
        self.bday = bday,
        self.amonth = amonth,
        self.ayear = ayear,
        self.aday = aday,
        self.new_group = new_group,
        self.address2 = address2,
        self.phone2 = phone2,
        self.notes = notes

